name: Build AridityTeam.Platform.* (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  MAIN_BASE_SLN: "AridityTeam.Platform.sln"
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          6.0.x
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Restore dependencies
      run: |
        nuget restore $Env:MAIN_BASE_SLN
        dotnet restore $Env:MAIN_BASE_SLN
      working-directory: ${{ github.workspace }}
      
    - name: Build
      run: msbuild $Env:MAIN_BASE_SLN /p:Configuration=Release /p:Platform="Any CPU"
      working-directory: ${{ github.workspace }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal $Env:MAIN_BASE_SLN
      working-directory: ${{ github.workspace }}